### PR TITLE
Initial commit with data files needed by PPSPixelDigiProducer

### PR DESCRIPTION
**Pull request by mundim**
Data files needed by the SimPPS/PPSPixelDigiProducer.

### CODE REVIEW

**Comment by smuzaffar** [comment]
ping bot

**Comment by smuzaffar** [comment]
@mundim , we can start the tests if there is cmssw PR which uses these files.

**Comment by mundim** [comment]
I'm replying to some comments in the review. This is part of a big PR, so to test it we will need all PR's to be merged. Thank you very much.

**Comment by mundim** [comment]
@smuzaffar finally a PR which uses this data files has been approved and it is time to test it. Can we proceed with this, please? Thanks.

**Comment by smuzaffar** [comment]
which pr is it? If there is already a PR which uses this data then please comment on the PR
```
please test with cms-data/SimPPS-PPSPixelDigiProducer#1
```
that should start the tests and set `test-approved` label for this pr

**Comment by smuzaffar** [comment]
ping?

**Comment by smuzaffar** [comment]
this is needed by https://github.com/cms-sw/cmssw/pull/27559 but code there is not yet part of any test

**Comment by mundim** [comment]
Dear @smuzaffar, I'm preparing a modification in a test config for the next week, but this will take some days because of deadlines in other tasks. Sorry about it. I'll come back to this issue soon.

**Comment by fabiocos** [comment]
@mundim @smuzaffar these new data files may enter, as they are not part of any test workflow we cannot test them until that is provided

**Comment by fabiocos** [comment]
@civanch FYI

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
@smuzaffar what is the issue with the bot here? I see that in cmsdist this package still needs to be added

**Comment by smuzaffar** [comment]
+externals
@fabiocos , I will check why bot fail. It could be that it was not able to use the correct branch of cmsdist

**Pull request merged**
